FROM nexus-docker.zacharyseguin.ca/alerts/base:latest AS base
FROM alpine:3.8
RUN apk --update --no-cache add ca-certificates
EXPOSE 2401
VOLUME /data
COPY --from=base /go/bin/resources /usr/bin/resources
USER 10001
ENTRYPOINT ["/usr/bin/resources"]
CMD ["serve", "--filesystem-path=/data"]
