// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources.proto

package resources

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import cap "github.com/alerting/alerts/cap"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// * Messages *
type GetRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_resources_46eb5c6bcb435970, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type GetResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType             string   `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_resources_46eb5c6bcb435970, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetResponse) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "resources.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "resources.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourcesServiceClient is the client API for ResourcesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourcesServiceClient interface {
	// Add a new alert. Returns a new resource with information to get it later from the Resource service.
	Add(ctx context.Context, in *cap.Resource, opts ...grpc.CallOption) (*cap.Resource, error)
	// Returns the resource for the given path.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type resourcesServiceClient struct {
	cc *grpc.ClientConn
}

func NewResourcesServiceClient(cc *grpc.ClientConn) ResourcesServiceClient {
	return &resourcesServiceClient{cc}
}

func (c *resourcesServiceClient) Add(ctx context.Context, in *cap.Resource, opts ...grpc.CallOption) (*cap.Resource, error) {
	out := new(cap.Resource)
	err := c.cc.Invoke(ctx, "/resources.ResourcesService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcesServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/resources.ResourcesService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourcesServiceServer is the server API for ResourcesService service.
type ResourcesServiceServer interface {
	// Add a new alert. Returns a new resource with information to get it later from the Resource service.
	Add(context.Context, *cap.Resource) (*cap.Resource, error)
	// Returns the resource for the given path.
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterResourcesServiceServer(s *grpc.Server, srv ResourcesServiceServer) {
	s.RegisterService(&_ResourcesService_serviceDesc, srv)
}

func _ResourcesService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(cap.Resource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcesServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourcesService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcesServiceServer).Add(ctx, req.(*cap.Resource))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourcesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resources.ResourcesService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcesServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourcesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resources.ResourcesService",
	HandlerType: (*ResourcesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ResourcesService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ResourcesService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resources.proto",
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor_resources_46eb5c6bcb435970) }

var fileDescriptor_resources_46eb5c6bcb435970 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xa9, 0x15, 0x71, 0x47, 0x45, 0x19, 0x50, 0x4a, 0xbc, 0x48, 0xbd, 0xec, 0x29, 0x05,
	0xf5, 0x2c, 0x78, 0xea, 0x3d, 0x7a, 0x97, 0x34, 0x3b, 0xd6, 0x40, 0xb3, 0x89, 0xc9, 0xac, 0xb0,
	0xff, 0x5e, 0x36, 0x61, 0x77, 0xb1, 0x87, 0xc0, 0xbc, 0x97, 0xf7, 0xe0, 0x7b, 0x70, 0x1d, 0x29,
	0xf9, 0x2e, 0x1a, 0x4a, 0x32, 0x44, 0xcf, 0x1e, 0xab, 0xc9, 0x10, 0xf5, 0xde, 0xf2, 0x77, 0xb7,
	0x93, 0xc6, 0xbb, 0x8d, 0x3e, 0x50, 0x64, 0xdb, 0xee, 0xcb, 0x91, 0x36, 0x46, 0x87, 0xe1, 0x95,
	0xd2, 0xba, 0x06, 0xd8, 0x12, 0x2b, 0xfa, 0xe9, 0x28, 0x31, 0x0a, 0x38, 0xff, 0xb2, 0x07, 0x6a,
	0xb5, 0xa3, 0xd5, 0xe2, 0x61, 0x51, 0x57, 0x6a, 0xd2, 0xeb, 0x57, 0xb8, 0xc8, 0xc9, 0x14, 0x7c,
	0x9b, 0x08, 0x11, 0x4e, 0x1b, 0xcd, 0x3a, 0xc7, 0x2e, 0x55, 0xbe, 0xf1, 0x1e, 0x2a, 0x67, 0x1d,
	0x7d, 0x72, 0x1f, 0x68, 0x75, 0x52, 0xfa, 0x83, 0xf1, 0xd1, 0x07, 0x7a, 0x72, 0x70, 0xa3, 0x46,
	0xc0, 0x77, 0x8a, 0xbf, 0xd6, 0x10, 0x3e, 0xc2, 0xf2, 0xad, 0x69, 0xf0, 0x4a, 0x0e, 0x40, 0xe3,
	0xaf, 0xf8, 0x2f, 0xf1, 0x05, 0x96, 0x5b, 0x62, 0xbc, 0x95, 0xf3, 0xe0, 0x19, 0x59, 0xdc, 0x1d,
	0xdb, 0x85, 0x6f, 0x77, 0x96, 0xf7, 0x3d, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9d, 0x4d,
	0xbc, 0x27, 0x01, 0x00, 0x00,
}
