// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boolean.proto

package alerts_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BooleanResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooleanResult) Reset()         { *m = BooleanResult{} }
func (m *BooleanResult) String() string { return proto.CompactTextString(m) }
func (*BooleanResult) ProtoMessage()    {}
func (*BooleanResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_boolean_3f763abd61ea4ded, []int{0}
}
func (m *BooleanResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooleanResult.Unmarshal(m, b)
}
func (m *BooleanResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooleanResult.Marshal(b, m, deterministic)
}
func (dst *BooleanResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooleanResult.Merge(dst, src)
}
func (m *BooleanResult) XXX_Size() int {
	return xxx_messageInfo_BooleanResult.Size(m)
}
func (m *BooleanResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BooleanResult.DiscardUnknown(m)
}

var xxx_messageInfo_BooleanResult proto.InternalMessageInfo

func (m *BooleanResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*BooleanResult)(nil), "alerts.protobuf.BooleanResult")
}

func init() { proto.RegisterFile("boolean.proto", fileDescriptor_boolean_3f763abd61ea4ded) }

var fileDescriptor_boolean_3f763abd61ea4ded = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xca, 0xcf, 0xcf,
	0x49, 0x4d, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xcc, 0x49, 0x2d, 0x2a,
	0x29, 0x86, 0xf0, 0x92, 0x4a, 0xd3, 0x94, 0xd4, 0xb9, 0x78, 0x9d, 0x20, 0x2a, 0x82, 0x52, 0x8b,
	0x4b, 0x73, 0x4a, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0xc0, 0x2c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e,
	0x20, 0x28, 0x2f, 0x89, 0x0d, 0xac, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x8d, 0x00,
	0x30, 0x51, 0x00, 0x00, 0x00,
}
