// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cap.proto

package cap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Info_Category int32

const (
	Info_CATEGORY_UNKNOWN Info_Category = 0
	Info_GEO              Info_Category = 1
	Info_MET              Info_Category = 2
	Info_SAFETY           Info_Category = 3
	Info_SECURITY         Info_Category = 4
	Info_RESCUE           Info_Category = 5
	Info_FIRE             Info_Category = 6
	Info_HEALTH           Info_Category = 7
	Info_ENV              Info_Category = 8
	Info_TRANSPORT        Info_Category = 9
	Info_INFRA            Info_Category = 10
	Info_CBRNE            Info_Category = 11
	Info_OTHER            Info_Category = 12
)

var Info_Category_name = map[int32]string{
	0:  "CATEGORY_UNKNOWN",
	1:  "GEO",
	2:  "MET",
	3:  "SAFETY",
	4:  "SECURITY",
	5:  "RESCUE",
	6:  "FIRE",
	7:  "HEALTH",
	8:  "ENV",
	9:  "TRANSPORT",
	10: "INFRA",
	11: "CBRNE",
	12: "OTHER",
}
var Info_Category_value = map[string]int32{
	"CATEGORY_UNKNOWN": 0,
	"GEO":              1,
	"MET":              2,
	"SAFETY":           3,
	"SECURITY":         4,
	"RESCUE":           5,
	"FIRE":             6,
	"HEALTH":           7,
	"ENV":              8,
	"TRANSPORT":        9,
	"INFRA":            10,
	"CBRNE":            11,
	"OTHER":            12,
}

func (x Info_Category) String() string {
	return proto.EnumName(Info_Category_name, int32(x))
}
func (Info_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 0}
}

type Info_ResponseType int32

const (
	Info_RESPONSE_TYPE_UNKNOWN Info_ResponseType = 0
	Info_SHELTER               Info_ResponseType = 1
	Info_EVACUATE              Info_ResponseType = 2
	Info_PREPARE               Info_ResponseType = 3
	Info_EXECUTE               Info_ResponseType = 4
	Info_AVOID                 Info_ResponseType = 5
	Info_MONITOR               Info_ResponseType = 6
	Info_ASSESS                Info_ResponseType = 7
	Info_ALL_CLEAR             Info_ResponseType = 8
	Info_NONE                  Info_ResponseType = 9
)

var Info_ResponseType_name = map[int32]string{
	0: "RESPONSE_TYPE_UNKNOWN",
	1: "SHELTER",
	2: "EVACUATE",
	3: "PREPARE",
	4: "EXECUTE",
	5: "AVOID",
	6: "MONITOR",
	7: "ASSESS",
	8: "ALL_CLEAR",
	9: "NONE",
}
var Info_ResponseType_value = map[string]int32{
	"RESPONSE_TYPE_UNKNOWN": 0,
	"SHELTER":               1,
	"EVACUATE":              2,
	"PREPARE":               3,
	"EXECUTE":               4,
	"AVOID":                 5,
	"MONITOR":               6,
	"ASSESS":                7,
	"ALL_CLEAR":             8,
	"NONE":                  9,
}

func (x Info_ResponseType) String() string {
	return proto.EnumName(Info_ResponseType_name, int32(x))
}
func (Info_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 1}
}

type Info_Urgency int32

const (
	Info_URGENCY_UNKNOWN Info_Urgency = 0
	Info_IMMEDIATE       Info_Urgency = 1
	Info_EXPECTED        Info_Urgency = 2
	Info_FUTURE          Info_Urgency = 3
	Info_PAST            Info_Urgency = 4
)

var Info_Urgency_name = map[int32]string{
	0: "URGENCY_UNKNOWN",
	1: "IMMEDIATE",
	2: "EXPECTED",
	3: "FUTURE",
	4: "PAST",
}
var Info_Urgency_value = map[string]int32{
	"URGENCY_UNKNOWN": 0,
	"IMMEDIATE":       1,
	"EXPECTED":        2,
	"FUTURE":          3,
	"PAST":            4,
}

func (x Info_Urgency) String() string {
	return proto.EnumName(Info_Urgency_name, int32(x))
}
func (Info_Urgency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 2}
}

type Info_Severity int32

const (
	Info_SEVERITY_UNKNOWN Info_Severity = 0
	Info_EXTREME          Info_Severity = 1
	Info_SEVERE           Info_Severity = 2
	Info_MODERATE         Info_Severity = 3
	Info_MINOR            Info_Severity = 4
)

var Info_Severity_name = map[int32]string{
	0: "SEVERITY_UNKNOWN",
	1: "EXTREME",
	2: "SEVERE",
	3: "MODERATE",
	4: "MINOR",
}
var Info_Severity_value = map[string]int32{
	"SEVERITY_UNKNOWN": 0,
	"EXTREME":          1,
	"SEVERE":           2,
	"MODERATE":         3,
	"MINOR":            4,
}

func (x Info_Severity) String() string {
	return proto.EnumName(Info_Severity_name, int32(x))
}
func (Info_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 3}
}

type Info_Certainty int32

const (
	Info_CERTAINTY_UNKNOWN Info_Certainty = 0
	Info_OBSERVED          Info_Certainty = 1
	Info_LIKELY            Info_Certainty = 2
	Info_POSSIBLE          Info_Certainty = 3
	Info_UNLIKELY          Info_Certainty = 4
)

var Info_Certainty_name = map[int32]string{
	0: "CERTAINTY_UNKNOWN",
	1: "OBSERVED",
	2: "LIKELY",
	3: "POSSIBLE",
	4: "UNLIKELY",
}
var Info_Certainty_value = map[string]int32{
	"CERTAINTY_UNKNOWN": 0,
	"OBSERVED":          1,
	"LIKELY":            2,
	"POSSIBLE":          3,
	"UNLIKELY":          4,
}

func (x Info_Certainty) String() string {
	return proto.EnumName(Info_Certainty_name, int32(x))
}
func (Info_Certainty) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 4}
}

type Alert_Status int32

const (
	Alert_STATUS_UNKNOWN Alert_Status = 0
	Alert_ACTUAL         Alert_Status = 1
	Alert_EXCERCISE      Alert_Status = 2
	Alert_SYSTEM         Alert_Status = 3
	Alert_TEST           Alert_Status = 4
	Alert_DRAFT          Alert_Status = 5
)

var Alert_Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "ACTUAL",
	2: "EXCERCISE",
	3: "SYSTEM",
	4: "TEST",
	5: "DRAFT",
}
var Alert_Status_value = map[string]int32{
	"STATUS_UNKNOWN": 0,
	"ACTUAL":         1,
	"EXCERCISE":      2,
	"SYSTEM":         3,
	"TEST":           4,
	"DRAFT":          5,
}

func (x Alert_Status) String() string {
	return proto.EnumName(Alert_Status_name, int32(x))
}
func (Alert_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{4, 0}
}

type Alert_MessageType int32

const (
	Alert_MESSAGE_TYPE_UNKNOWN Alert_MessageType = 0
	Alert_ALERT                Alert_MessageType = 1
	Alert_UPDATE               Alert_MessageType = 2
	Alert_CANCEL               Alert_MessageType = 3
	Alert_ACK                  Alert_MessageType = 4
	Alert_ERROR                Alert_MessageType = 5
)

var Alert_MessageType_name = map[int32]string{
	0: "MESSAGE_TYPE_UNKNOWN",
	1: "ALERT",
	2: "UPDATE",
	3: "CANCEL",
	4: "ACK",
	5: "ERROR",
}
var Alert_MessageType_value = map[string]int32{
	"MESSAGE_TYPE_UNKNOWN": 0,
	"ALERT":                1,
	"UPDATE":               2,
	"CANCEL":               3,
	"ACK":                  4,
	"ERROR":                5,
}

func (x Alert_MessageType) String() string {
	return proto.EnumName(Alert_MessageType_name, int32(x))
}
func (Alert_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{4, 1}
}

type Alert_Scope int32

const (
	Alert_SCOPE_UNKNOWN Alert_Scope = 0
	Alert_PUBLIC        Alert_Scope = 1
	Alert_RESTRICTED    Alert_Scope = 2
	Alert_PRIVATE       Alert_Scope = 3
)

var Alert_Scope_name = map[int32]string{
	0: "SCOPE_UNKNOWN",
	1: "PUBLIC",
	2: "RESTRICTED",
	3: "PRIVATE",
}
var Alert_Scope_value = map[string]int32{
	"SCOPE_UNKNOWN": 0,
	"PUBLIC":        1,
	"RESTRICTED":    2,
	"PRIVATE":       3,
}

func (x Alert_Scope) String() string {
	return proto.EnumName(Alert_Scope_name, int32(x))
}
func (Alert_Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{4, 2}
}

type Reference struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier           string               `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Sender               string               `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Sent                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{0}
}
func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (dst *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(dst, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reference) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Reference) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Reference) GetSent() *timestamp.Timestamp {
	if m != nil {
		return m.Sent
	}
	return nil
}

type Resource struct {
	// The text describing the type and content of the resource file
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The identifier of the MIME content type and sub-type describing the resource file
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The integer indicating the size of the resource file
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// The identifier of the hyperlink for the resource file
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// The base64 encoded data content of the resource file
	DerefUri []byte `protobuf:"bytes,5,opt,name=deref_uri,json=derefUri,proto3" json:"deref_uri,omitempty"`
	// The code representing the digital digest ("hash") computed from the resource file
	Digest               string   `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{1}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Resource) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *Resource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Resource) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Resource) GetDerefUri() []byte {
	if m != nil {
		return m.DerefUri
	}
	return nil
}

func (m *Resource) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

type Area struct {
	// The text describing the affected area of the alert message
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// The paired values of points defining a polygon that delieantes the affected area of the alert message
	Polygons []*Area_Polygon `protobuf:"bytes,2,rep,name=polygons,proto3" json:"polygons,omitempty"`
	// The paried values of a point and radius delineating the affected area of the alert message
	Circles []*Area_Circle `protobuf:"bytes,3,rep,name=circles,proto3" json:"circles,omitempty"`
	// The geographic code delienating the affected area of the alert message
	Geocodes map[string]*_struct.ListValue `protobuf:"bytes,4,rep,name=geocodes,proto3" json:"geocodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The specific or minimum altitude of the affected area of the alert message
	Altitude float64 `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// The maximum altitude of the affected area of the alert message
	Ceiling              float64  `protobuf:"fixed64,6,opt,name=ceiling,proto3" json:"ceiling,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{2}
}
func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (dst *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(dst, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Area) GetPolygons() []*Area_Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

func (m *Area) GetCircles() []*Area_Circle {
	if m != nil {
		return m.Circles
	}
	return nil
}

func (m *Area) GetGeocodes() map[string]*_struct.ListValue {
	if m != nil {
		return m.Geocodes
	}
	return nil
}

func (m *Area) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Area) GetCeiling() float64 {
	if m != nil {
		return m.Ceiling
	}
	return 0
}

type Area_Polygon struct {
	Type                 string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates          []*_struct.ListValue `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Area_Polygon) Reset()         { *m = Area_Polygon{} }
func (m *Area_Polygon) String() string { return proto.CompactTextString(m) }
func (*Area_Polygon) ProtoMessage()    {}
func (*Area_Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{2, 0}
}
func (m *Area_Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area_Polygon.Unmarshal(m, b)
}
func (m *Area_Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area_Polygon.Marshal(b, m, deterministic)
}
func (dst *Area_Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area_Polygon.Merge(dst, src)
}
func (m *Area_Polygon) XXX_Size() int {
	return xxx_messageInfo_Area_Polygon.Size(m)
}
func (m *Area_Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Area_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Area_Polygon proto.InternalMessageInfo

func (m *Area_Polygon) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Area_Polygon) GetCoordinates() []*_struct.ListValue {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Area_Circle struct {
	Type                 string    `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates          []float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Radius               float64   `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Area_Circle) Reset()         { *m = Area_Circle{} }
func (m *Area_Circle) String() string { return proto.CompactTextString(m) }
func (*Area_Circle) ProtoMessage()    {}
func (*Area_Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{2, 1}
}
func (m *Area_Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area_Circle.Unmarshal(m, b)
}
func (m *Area_Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area_Circle.Marshal(b, m, deterministic)
}
func (dst *Area_Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area_Circle.Merge(dst, src)
}
func (m *Area_Circle) XXX_Size() int {
	return xxx_messageInfo_Area_Circle.Size(m)
}
func (m *Area_Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Area_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Area_Circle proto.InternalMessageInfo

func (m *Area_Circle) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Area_Circle) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Area_Circle) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type Info struct {
	// The code denoting the language of the info sub-element of the alert message
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// The code denoting the category of the subject event of the alert message
	Categories []Info_Category `protobuf:"varint,2,rep,packed,name=categories,proto3,enum=cap.Info_Category" json:"categories,omitempty"`
	// The text denoting the type of the subject event of the alert message
	Event string `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	// The code denoting the type of action recommended for the target audience
	ResponseTypes []Info_ResponseType `protobuf:"varint,4,rep,packed,name=response_types,json=responseTypes,proto3,enum=cap.Info_ResponseType" json:"response_types,omitempty"`
	// The code denoting the urgency of the subject event of the alert message
	Urgency Info_Urgency `protobuf:"varint,5,opt,name=urgency,proto3,enum=cap.Info_Urgency" json:"urgency,omitempty"`
	// The code denoting the severity of the subject event of the alert message
	Severity Info_Severity `protobuf:"varint,6,opt,name=severity,proto3,enum=cap.Info_Severity" json:"severity,omitempty"`
	// The code denoting the certainty of the subject event of hte alert message
	Certainty Info_Certainty `protobuf:"varint,7,opt,name=certainty,proto3,enum=cap.Info_Certainty" json:"certainty,omitempty"`
	// The text describing the intended audience of the alert message
	Audience   string                        `protobuf:"bytes,8,opt,name=audience,proto3" json:"audience,omitempty"`
	EventCodes map[string]*_struct.ListValue `protobuf:"bytes,9,rep,name=event_codes,json=eventCodes,proto3" json:"event_codes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The effective time of the information of the alert message
	Effective *timestamp.Timestamp `protobuf:"bytes,10,opt,name=effective,proto3" json:"effective,omitempty"`
	// The expected time of the beginning of hte subject event of the alert message
	Onset *timestamp.Timestamp `protobuf:"bytes,11,opt,name=onset,proto3" json:"onset,omitempty"`
	// The expiry time of the information of the alert message
	Expires *timestamp.Timestamp `protobuf:"bytes,12,opt,name=expires,proto3" json:"expires,omitempty"`
	// The text naming the originator of the alert message
	SenderName string `protobuf:"bytes,13,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	// The text headling of the alert message
	Headline string `protobuf:"bytes,14,opt,name=headline,proto3" json:"headline,omitempty"`
	// The text describing the subject event of the alert message
	Description string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	// The text describing the recommended action to be taken by the recipients of the alert message
	Instruction string `protobuf:"bytes,16,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// The identifier of the hyperlink associating additional information with the alert message
	Web string `protobuf:"bytes,17,opt,name=web,proto3" json:"web,omitempty"`
	// The text describing the contact for follow-up and confirmation of the alert message
	Contact string `protobuf:"bytes,18,opt,name=contact,proto3" json:"contact,omitempty"`
	// A system-specific additional parameter associated with the alert message
	Parameters map[string]*_struct.ListValue `protobuf:"bytes,19,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The container for all componment parts of the resource sub-element of the alert message
	Resources []*Resource `protobuf:"bytes,20,rep,name=resources,proto3" json:"resources,omitempty"`
	// The container for all component parts of the area sub-element of the info sub-element of the alert message
	Areas                []*Area  `protobuf:"bytes,21,rep,name=areas,proto3" json:"areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Info) GetCategories() []Info_Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Info) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Info) GetResponseTypes() []Info_ResponseType {
	if m != nil {
		return m.ResponseTypes
	}
	return nil
}

func (m *Info) GetUrgency() Info_Urgency {
	if m != nil {
		return m.Urgency
	}
	return Info_URGENCY_UNKNOWN
}

func (m *Info) GetSeverity() Info_Severity {
	if m != nil {
		return m.Severity
	}
	return Info_SEVERITY_UNKNOWN
}

func (m *Info) GetCertainty() Info_Certainty {
	if m != nil {
		return m.Certainty
	}
	return Info_CERTAINTY_UNKNOWN
}

func (m *Info) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *Info) GetEventCodes() map[string]*_struct.ListValue {
	if m != nil {
		return m.EventCodes
	}
	return nil
}

func (m *Info) GetEffective() *timestamp.Timestamp {
	if m != nil {
		return m.Effective
	}
	return nil
}

func (m *Info) GetOnset() *timestamp.Timestamp {
	if m != nil {
		return m.Onset
	}
	return nil
}

func (m *Info) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *Info) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *Info) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *Info) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Info) GetInstruction() string {
	if m != nil {
		return m.Instruction
	}
	return ""
}

func (m *Info) GetWeb() string {
	if m != nil {
		return m.Web
	}
	return ""
}

func (m *Info) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *Info) GetParameters() map[string]*_struct.ListValue {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Info) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Info) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

// A system-specific code identifying the event type of the alert message
type Info_ListString struct {
	V                    []string `protobuf:"bytes,1,rep,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info_ListString) Reset()         { *m = Info_ListString{} }
func (m *Info_ListString) String() string { return proto.CompactTextString(m) }
func (*Info_ListString) ProtoMessage()    {}
func (*Info_ListString) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{3, 0}
}
func (m *Info_ListString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info_ListString.Unmarshal(m, b)
}
func (m *Info_ListString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info_ListString.Marshal(b, m, deterministic)
}
func (dst *Info_ListString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info_ListString.Merge(dst, src)
}
func (m *Info_ListString) XXX_Size() int {
	return xxx_messageInfo_Info_ListString.Size(m)
}
func (m *Info_ListString) XXX_DiscardUnknown() {
	xxx_messageInfo_Info_ListString.DiscardUnknown(m)
}

var xxx_messageInfo_Info_ListString proto.InternalMessageInfo

func (m *Info_ListString) GetV() []string {
	if m != nil {
		return m.V
	}
	return nil
}

type Alert struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The identifier of the alert message
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// The identifier of the sender of the alert message
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// The time and date of the origination of the alert message
	Sent *timestamp.Timestamp `protobuf:"bytes,4,opt,name=sent,proto3" json:"sent,omitempty"`
	// The code denoting the appropriate handling of the alert message
	Status Alert_Status `protobuf:"varint,5,opt,name=status,proto3,enum=cap.Alert_Status" json:"status,omitempty"`
	// The code denoting the nature of the alert message
	MessageType Alert_MessageType `protobuf:"varint,6,opt,name=message_type,json=messageType,proto3,enum=cap.Alert_MessageType" json:"message_type,omitempty"`
	// The text identifying the source of the alert message
	Source string `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	// The code denoting the intended distribution of the alert message
	Scope Alert_Scope `protobuf:"varint,8,opt,name=scope,proto3,enum=cap.Alert_Scope" json:"scope,omitempty"`
	// The text describing the rule for limiting distribution of the restricted alert message
	Restriction string `protobuf:"bytes,9,opt,name=restriction,proto3" json:"restriction,omitempty"`
	// The group listing of intended recipients of the alert message
	Addresses []string `protobuf:"bytes,10,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// The code denoting the special handling of the alert message
	Code []string `protobuf:"bytes,11,rep,name=code,proto3" json:"code,omitempty"`
	// The text describing the purpose or significance of the alert message
	Note string `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	// The group listing identifying earlier message(s) by the alert message
	References []*Reference `protobuf:"bytes,13,rep,name=references,proto3" json:"references,omitempty"`
	// The group listing naming the referent incident(s) of the alert message
	Incidents []string `protobuf:"bytes,14,rep,name=incidents,proto3" json:"incidents,omitempty"`
	// The container for all component parts of the info sub-element of the alert message
	Infos []*Info `protobuf:"bytes,15,rep,name=infos,proto3" json:"infos,omitempty"`
	// The alert has been superseded
	Superseded           bool     `protobuf:"varint,16,opt,name=superseded,proto3" json:"superseded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Alert) Reset()         { *m = Alert{} }
func (m *Alert) String() string { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()    {}
func (*Alert) Descriptor() ([]byte, []int) {
	return fileDescriptor_cap_70cb05609a3a940c, []int{4}
}
func (m *Alert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Alert.Unmarshal(m, b)
}
func (m *Alert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Alert.Marshal(b, m, deterministic)
}
func (dst *Alert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Alert.Merge(dst, src)
}
func (m *Alert) XXX_Size() int {
	return xxx_messageInfo_Alert.Size(m)
}
func (m *Alert) XXX_DiscardUnknown() {
	xxx_messageInfo_Alert.DiscardUnknown(m)
}

var xxx_messageInfo_Alert proto.InternalMessageInfo

func (m *Alert) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Alert) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Alert) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Alert) GetSent() *timestamp.Timestamp {
	if m != nil {
		return m.Sent
	}
	return nil
}

func (m *Alert) GetStatus() Alert_Status {
	if m != nil {
		return m.Status
	}
	return Alert_STATUS_UNKNOWN
}

func (m *Alert) GetMessageType() Alert_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Alert_MESSAGE_TYPE_UNKNOWN
}

func (m *Alert) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Alert) GetScope() Alert_Scope {
	if m != nil {
		return m.Scope
	}
	return Alert_SCOPE_UNKNOWN
}

func (m *Alert) GetRestriction() string {
	if m != nil {
		return m.Restriction
	}
	return ""
}

func (m *Alert) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Alert) GetCode() []string {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Alert) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Alert) GetReferences() []*Reference {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Alert) GetIncidents() []string {
	if m != nil {
		return m.Incidents
	}
	return nil
}

func (m *Alert) GetInfos() []*Info {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *Alert) GetSuperseded() bool {
	if m != nil {
		return m.Superseded
	}
	return false
}

func init() {
	proto.RegisterType((*Reference)(nil), "cap.Reference")
	proto.RegisterType((*Resource)(nil), "cap.Resource")
	proto.RegisterType((*Area)(nil), "cap.Area")
	proto.RegisterMapType((map[string]*_struct.ListValue)(nil), "cap.Area.GeocodesEntry")
	proto.RegisterType((*Area_Polygon)(nil), "cap.Area.Polygon")
	proto.RegisterType((*Area_Circle)(nil), "cap.Area.Circle")
	proto.RegisterType((*Info)(nil), "cap.Info")
	proto.RegisterMapType((map[string]*_struct.ListValue)(nil), "cap.Info.EventCodesEntry")
	proto.RegisterMapType((map[string]*_struct.ListValue)(nil), "cap.Info.ParametersEntry")
	proto.RegisterType((*Info_ListString)(nil), "cap.Info.ListString")
	proto.RegisterType((*Alert)(nil), "cap.Alert")
	proto.RegisterEnum("cap.Info_Category", Info_Category_name, Info_Category_value)
	proto.RegisterEnum("cap.Info_ResponseType", Info_ResponseType_name, Info_ResponseType_value)
	proto.RegisterEnum("cap.Info_Urgency", Info_Urgency_name, Info_Urgency_value)
	proto.RegisterEnum("cap.Info_Severity", Info_Severity_name, Info_Severity_value)
	proto.RegisterEnum("cap.Info_Certainty", Info_Certainty_name, Info_Certainty_value)
	proto.RegisterEnum("cap.Alert_Status", Alert_Status_name, Alert_Status_value)
	proto.RegisterEnum("cap.Alert_MessageType", Alert_MessageType_name, Alert_MessageType_value)
	proto.RegisterEnum("cap.Alert_Scope", Alert_Scope_name, Alert_Scope_value)
}

func init() { proto.RegisterFile("cap.proto", fileDescriptor_cap_70cb05609a3a940c) }

var fileDescriptor_cap_70cb05609a3a940c = []byte{
	// 1566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x4b, 0x6f, 0xe3, 0xc8,
	0x11, 0x0e, 0xad, 0x17, 0x59, 0x7a, 0x0c, 0xa7, 0xe7, 0x11, 0xae, 0xb2, 0xc8, 0x18, 0x3a, 0x04,
	0x4e, 0x16, 0xd1, 0x26, 0xde, 0x1c, 0x76, 0x17, 0xc9, 0x81, 0x43, 0xb7, 0x3d, 0xc2, 0x48, 0xa4,
	0xd2, 0xa4, 0xbc, 0x36, 0x02, 0xc4, 0xe0, 0x90, 0x2d, 0xa5, 0x11, 0x89, 0x14, 0xba, 0x29, 0x6f,
	0x94, 0x6b, 0x80, 0xfc, 0x89, 0xbd, 0x06, 0xc8, 0x9f, 0xcc, 0x21, 0xe8, 0x6e, 0x52, 0xa2, 0xed,
	0x20, 0x93, 0xc3, 0x00, 0xb9, 0x75, 0x57, 0x7d, 0x5d, 0xfc, 0xaa, 0xab, 0xea, 0x63, 0x83, 0x95,
	0xc4, 0xdb, 0xf1, 0x96, 0xe7, 0x45, 0x8e, 0x1a, 0x49, 0xbc, 0x1d, 0xbe, 0x59, 0xe5, 0xf9, 0x6a,
	0x4d, 0xbf, 0x54, 0xa6, 0x0f, 0xbb, 0xe5, 0x97, 0x05, 0xdb, 0x50, 0x51, 0xc4, 0x9b, 0x12, 0x35,
	0xfc, 0xfc, 0x31, 0x40, 0x14, 0x7c, 0x97, 0x14, 0xda, 0x3b, 0xfa, 0x9b, 0x01, 0x16, 0xa1, 0x4b,
	0xca, 0x69, 0x96, 0x50, 0x34, 0x80, 0x13, 0x96, 0x3a, 0xc6, 0xa9, 0x71, 0x66, 0x91, 0x13, 0x96,
	0xa2, 0x9f, 0x02, 0xb0, 0x94, 0x66, 0x05, 0x5b, 0x32, 0xca, 0x9d, 0x13, 0x65, 0xaf, 0x59, 0xd0,
	0x6b, 0x68, 0x0b, 0x9a, 0xa5, 0x94, 0x3b, 0x0d, 0xe5, 0x2b, 0x77, 0x68, 0x0c, 0x4d, 0x41, 0xb3,
	0xc2, 0x69, 0x9e, 0x1a, 0x67, 0xdd, 0xf3, 0xe1, 0x58, 0x53, 0x18, 0x57, 0x14, 0xc6, 0x51, 0xc5,
	0x91, 0x28, 0xdc, 0xe8, 0x1f, 0x06, 0x98, 0x84, 0x8a, 0x7c, 0xc7, 0x13, 0x8a, 0x4e, 0xa1, 0x9b,
	0x52, 0x91, 0x70, 0xb6, 0x2d, 0x58, 0x9e, 0x95, 0x6c, 0xea, 0x26, 0xf4, 0x13, 0xb0, 0x36, 0x6c,
	0x43, 0xef, 0x8a, 0xfd, 0x96, 0x96, 0xac, 0x4c, 0x69, 0x88, 0xf6, 0x5b, 0x8a, 0x10, 0x34, 0x05,
	0xfb, 0x2b, 0x55, 0x8c, 0x1a, 0x44, 0xad, 0x91, 0x0d, 0x8d, 0x1d, 0x67, 0x8a, 0x8e, 0x45, 0xe4,
	0x52, 0x86, 0x48, 0x29, 0xa7, 0xcb, 0x3b, 0x69, 0x6f, 0x9d, 0x1a, 0x67, 0x3d, 0x62, 0x2a, 0xc3,
	0x82, 0x33, 0x99, 0x56, 0xca, 0x56, 0x54, 0x14, 0x4e, 0x5b, 0xa7, 0xa5, 0x77, 0xa3, 0x7f, 0x35,
	0xa0, 0xe9, 0x72, 0x1a, 0xff, 0x0f, 0x14, 0x7f, 0x09, 0xe6, 0x36, 0x5f, 0xef, 0x57, 0x79, 0x26,
	0x9c, 0x93, 0xd3, 0xc6, 0x59, 0xf7, 0xfc, 0xf9, 0x58, 0x56, 0x4e, 0x1e, 0x1f, 0xcf, 0xb5, 0x87,
	0x1c, 0x20, 0xe8, 0x17, 0xd0, 0x49, 0x18, 0x4f, 0xd6, 0x54, 0x38, 0x0d, 0x85, 0xb6, 0x8f, 0x68,
	0x4f, 0x39, 0x48, 0x05, 0x40, 0x5f, 0x81, 0xb9, 0xa2, 0x79, 0x92, 0xa7, 0x54, 0x38, 0x4d, 0x05,
	0xfe, 0xf1, 0x11, 0x7c, 0x55, 0x7a, 0x70, 0x56, 0xf0, 0x3d, 0x39, 0x00, 0xd1, 0x10, 0xcc, 0x78,
	0x5d, 0xb0, 0x62, 0x97, 0x52, 0x95, 0xae, 0x41, 0x0e, 0x7b, 0xe4, 0x40, 0x27, 0xa1, 0x6c, 0xcd,
	0xb2, 0x95, 0xca, 0xd7, 0x20, 0xd5, 0x76, 0xf8, 0x07, 0xe8, 0x94, 0x5c, 0xe5, 0xb5, 0xaa, 0xeb,
	0xd6, 0xb9, 0xaa, 0x35, 0xfa, 0x2d, 0x74, 0x93, 0x3c, 0xe7, 0x29, 0xcb, 0xe2, 0x82, 0x56, 0x79,
	0x3e, 0xad, 0xf6, 0x94, 0x89, 0xe2, 0x3a, 0x5e, 0xef, 0x28, 0xa9, 0xc3, 0x87, 0xd7, 0xd0, 0xd6,
	0xa9, 0xfd, 0xc7, 0xd8, 0xa7, 0x4f, 0x63, 0x1b, 0x0f, 0xce, 0xcb, 0x2a, 0xf1, 0x38, 0x65, 0x3b,
	0xa1, 0x4a, 0x6d, 0x90, 0x72, 0x37, 0xfc, 0x0e, 0xfa, 0x0f, 0x6e, 0x41, 0x56, 0xff, 0xcf, 0x74,
	0x5f, 0x46, 0x97, 0x4b, 0xf4, 0x2b, 0x68, 0xdd, 0x4b, 0x42, 0xaa, 0x79, 0xfe, 0x3b, 0x65, 0x0d,
	0xfc, 0xf6, 0xe4, 0x6b, 0x63, 0xf4, 0xf7, 0x3e, 0x34, 0x27, 0xd9, 0x32, 0x97, 0x97, 0xb9, 0x8e,
	0xb3, 0xd5, 0x2e, 0x5e, 0x55, 0x9c, 0x0f, 0x7b, 0x74, 0x0e, 0x90, 0xc4, 0x05, 0x5d, 0xe5, 0x9c,
	0x95, 0xb4, 0x07, 0xe7, 0x48, 0xd5, 0x47, 0x1e, 0x1d, 0x7b, 0xda, 0xb7, 0x27, 0x35, 0x14, 0x7a,
	0x09, 0x2d, 0x7a, 0x2f, 0xe7, 0x45, 0x4f, 0x91, 0xde, 0xa0, 0xdf, 0xc1, 0x80, 0x53, 0xb1, 0xcd,
	0x33, 0xa1, 0x3b, 0x5d, 0x57, 0x7b, 0x70, 0xfe, 0xfa, 0x18, 0x8d, 0x94, 0x7e, 0xd9, 0xf8, 0xa4,
	0xcf, 0x6b, 0x3b, 0x81, 0xbe, 0x80, 0xce, 0x8e, 0xaf, 0x68, 0x96, 0xec, 0x55, 0xc1, 0x07, 0x65,
	0x03, 0xaa, 0x73, 0x0b, 0xed, 0x20, 0x15, 0x02, 0x8d, 0xc1, 0x14, 0xf4, 0x9e, 0x72, 0x56, 0xec,
	0x55, 0x0f, 0x3c, 0xe0, 0x1c, 0x96, 0x1e, 0x72, 0xc0, 0xa0, 0x5f, 0x83, 0x95, 0x50, 0x5e, 0xc4,
	0x2c, 0x2b, 0xf6, 0x4e, 0x47, 0x1d, 0x78, 0x51, 0x4b, 0xb2, 0x72, 0x91, 0x23, 0x4a, 0x75, 0xe0,
	0x2e, 0x65, 0x52, 0x67, 0x1c, 0x53, 0x5f, 0x5a, 0xb5, 0x47, 0xdf, 0x42, 0x57, 0xe5, 0x7c, 0xa7,
	0xbb, 0xda, 0x52, 0x8d, 0xf4, 0xd9, 0x31, 0x20, 0x96, 0x4e, 0xef, 0xd8, 0xd7, 0x40, 0x0f, 0x06,
	0xf4, 0x35, 0x58, 0x74, 0xb9, 0xa4, 0x49, 0xc1, 0xee, 0xa9, 0x03, 0x1f, 0x15, 0x9c, 0x23, 0x58,
	0x76, 0x81, 0xbc, 0xae, 0xc2, 0xe9, 0x7e, 0xf4, 0x94, 0x06, 0xa2, 0xdf, 0x40, 0x87, 0xfe, 0x65,
	0xcb, 0x38, 0x15, 0x4e, 0xef, 0xa3, 0x67, 0x2a, 0x28, 0x7a, 0x03, 0x5d, 0xad, 0x8b, 0x77, 0x59,
	0xbc, 0xa1, 0x4e, 0x5f, 0xcb, 0xa8, 0x36, 0xf9, 0xf1, 0x86, 0xca, 0xab, 0xf9, 0x13, 0x8d, 0xd3,
	0x35, 0xcb, 0xa8, 0x33, 0xd0, 0x57, 0x53, 0xed, 0x1f, 0x4b, 0xcd, 0xb3, 0xa7, 0x52, 0x73, 0x0a,
	0x5d, 0x96, 0x69, 0x51, 0x97, 0x08, 0x5b, 0x23, 0x6a, 0x26, 0x39, 0x00, 0xdf, 0xd3, 0x0f, 0xce,
	0x73, 0x3d, 0x00, 0xdf, 0xd3, 0x0f, 0x6a, 0xe4, 0xf3, 0xac, 0x88, 0x93, 0xc2, 0x41, 0xca, 0x5a,
	0x6d, 0xd1, 0x37, 0x00, 0xdb, 0x98, 0xc7, 0x1b, 0x5a, 0x50, 0x2e, 0x9c, 0x17, 0x8f, 0x2b, 0x31,
	0x3f, 0xf8, 0xca, 0x4a, 0x1c, 0xc1, 0xe8, 0x0b, 0xb0, 0x78, 0x29, 0xe2, 0xc2, 0x79, 0xa9, 0x4e,
	0xf6, 0xd5, 0xc9, 0x4a, 0xda, 0xc9, 0xd1, 0x8f, 0xde, 0x40, 0x2b, 0xe6, 0x34, 0x16, 0xce, 0x2b,
	0x05, 0xb4, 0x0e, 0x12, 0x46, 0xb4, 0x7d, 0x38, 0x04, 0x90, 0x53, 0x18, 0x16, 0x9c, 0x65, 0x2b,
	0xd4, 0x03, 0xe3, 0xde, 0x31, 0x4e, 0x1b, 0x67, 0x16, 0x31, 0xee, 0x87, 0xb7, 0xf0, 0xec, 0x51,
	0x4b, 0x7c, 0xaa, 0x21, 0x97, 0xa1, 0x1f, 0xe5, 0xf8, 0xc9, 0xf4, 0xe3, 0x9f, 0x06, 0x98, 0xd5,
	0xfc, 0xa3, 0x97, 0x60, 0x7b, 0x6e, 0x84, 0xaf, 0x02, 0x72, 0x7b, 0xb7, 0xf0, 0xdf, 0xfb, 0xc1,
	0x77, 0xbe, 0xfd, 0x23, 0xd4, 0x81, 0xc6, 0x15, 0x0e, 0x6c, 0x43, 0x2e, 0x66, 0x38, 0xb2, 0x4f,
	0x10, 0x40, 0x3b, 0x74, 0x2f, 0x71, 0x74, 0x6b, 0x37, 0x50, 0x0f, 0xcc, 0x10, 0x7b, 0x0b, 0x32,
	0x89, 0x6e, 0xed, 0xa6, 0xf4, 0x10, 0x1c, 0x7a, 0x0b, 0x6c, 0xb7, 0x90, 0x09, 0xcd, 0xcb, 0x09,
	0xc1, 0x76, 0x5b, 0x5a, 0xdf, 0x61, 0x77, 0x1a, 0xbd, 0xb3, 0x3b, 0x32, 0x08, 0xf6, 0xaf, 0x6d,
	0x13, 0xf5, 0xc1, 0x8a, 0x88, 0xeb, 0x87, 0xf3, 0x80, 0x44, 0xb6, 0x85, 0x2c, 0x68, 0x4d, 0xfc,
	0x4b, 0xe2, 0xda, 0x20, 0x97, 0xde, 0x5b, 0xe2, 0x63, 0xbb, 0x2b, 0x97, 0x41, 0xf4, 0x0e, 0x13,
	0xbb, 0x37, 0xfa, 0xc1, 0x80, 0x5e, 0x5d, 0x5b, 0xd0, 0x67, 0xf0, 0x8a, 0xe0, 0x70, 0x1e, 0xf8,
	0x21, 0xbe, 0x8b, 0x6e, 0xe7, 0xb8, 0x46, 0xb9, 0x0b, 0x9d, 0xf0, 0x1d, 0x9e, 0x46, 0x98, 0xd8,
	0x86, 0x64, 0x88, 0xaf, 0x5d, 0x6f, 0xe1, 0x46, 0xd8, 0x3e, 0x91, 0xae, 0x39, 0xc1, 0x73, 0x97,
	0x60, 0xbb, 0x21, 0x37, 0xf8, 0x06, 0x7b, 0x8b, 0x08, 0xdb, 0x4d, 0xf9, 0x2d, 0xf7, 0x3a, 0x98,
	0x5c, 0xd8, 0x2d, 0x69, 0x9f, 0x05, 0xfe, 0x24, 0x0a, 0x88, 0x66, 0xef, 0x86, 0x21, 0x0e, 0x43,
	0xbb, 0x23, 0x49, 0xbb, 0xd3, 0xe9, 0x9d, 0x37, 0xc5, 0x2e, 0xb1, 0x4d, 0x99, 0xa2, 0x1f, 0xf8,
	0xd8, 0xb6, 0x46, 0xbf, 0x87, 0x4e, 0x29, 0x60, 0xe8, 0x05, 0x3c, 0x5b, 0x90, 0x2b, 0xec, 0x7b,
	0xf5, 0x4b, 0xec, 0x83, 0x35, 0x99, 0xcd, 0xf0, 0xc5, 0x44, 0xb2, 0xd0, 0x9c, 0x6e, 0xe6, 0xd8,
	0x8b, 0xf0, 0x85, 0xbe, 0xcf, 0xcb, 0x45, 0xb4, 0x50, 0x94, 0x4c, 0x68, 0xce, 0xdd, 0x30, 0xb2,
	0x9b, 0x23, 0x02, 0x66, 0xa5, 0x72, 0xb2, 0x32, 0x21, 0xbe, 0xc6, 0xf2, 0x96, 0x1f, 0xa6, 0x89,
	0x6f, 0x22, 0x82, 0x67, 0x32, 0xa4, 0x2c, 0x8a, 0x84, 0xc8, 0x24, 0x7b, 0x60, 0xce, 0x82, 0x0b,
	0x4c, 0xe4, 0xc7, 0x1a, 0x32, 0xb1, 0xd9, 0xc4, 0x0f, 0x88, 0xdd, 0x1c, 0xdd, 0x80, 0x75, 0x10,
	0x42, 0xf4, 0x0a, 0x9e, 0x7b, 0x98, 0x44, 0xee, 0xc4, 0x7f, 0x10, 0xb5, 0x07, 0x66, 0xf0, 0x36,
	0xc4, 0xe4, 0x1a, 0x5f, 0xe8, 0xb0, 0xd3, 0xc9, 0x7b, 0x3c, 0xbd, 0xd5, 0x61, 0xe7, 0x41, 0x18,
	0x4e, 0xde, 0x4e, 0xb1, 0xae, 0xfc, 0xc2, 0x2f, 0x7d, 0xcd, 0xd1, 0x0f, 0x6d, 0x68, 0xb9, 0x6b,
	0xca, 0x8b, 0xff, 0xd7, 0x83, 0x0d, 0xfd, 0x1c, 0xda, 0xa2, 0x88, 0x8b, 0x9d, 0x78, 0xf0, 0x6f,
	0x51, 0x9c, 0xc6, 0xa1, 0x72, 0x90, 0x12, 0x80, 0xbe, 0x81, 0xde, 0x86, 0x0a, 0x11, 0xaf, 0xca,
	0xf7, 0x9a, 0xfe, 0xbd, 0xbc, 0xae, 0x1d, 0x98, 0x69, 0xb7, 0xfa, 0x89, 0x75, 0x37, 0xc7, 0x8d,
	0x62, 0xab, 0xe4, 0x42, 0xfd, 0x62, 0x24, 0x5b, 0xfd, 0x42, 0xfc, 0x19, 0xb4, 0x44, 0x92, 0x6f,
	0xf5, 0x7f, 0x64, 0x50, 0xbd, 0x95, 0xf4, 0xc7, 0xa5, 0x9d, 0x68, 0xb7, 0x54, 0x46, 0x4e, 0x45,
	0xc1, 0x99, 0x56, 0x46, 0x4b, 0x2b, 0x63, 0xcd, 0x84, 0x3e, 0x07, 0x2b, 0x4e, 0x53, 0x4e, 0x85,
	0xa0, 0xc2, 0x01, 0x25, 0x2f, 0x47, 0x83, 0x7c, 0x97, 0xc8, 0x1f, 0x92, 0xd3, 0x55, 0x0e, 0xb5,
	0x96, 0xb6, 0x2c, 0x2f, 0xa8, 0xd2, 0x7f, 0x8b, 0xa8, 0x35, 0x1a, 0x03, 0xf0, 0xea, 0x0d, 0x2d,
	0x9c, 0xbe, 0x12, 0xb4, 0x41, 0xa9, 0x7c, 0xa5, 0x99, 0xd4, 0x10, 0xf2, 0xab, 0x2c, 0x4b, 0x54,
	0x59, 0x84, 0x33, 0xd0, 0x5f, 0x3d, 0x18, 0xa4, 0x32, 0xb2, 0x6c, 0x99, 0x0b, 0xe7, 0x59, 0x4d,
	0x19, 0xa5, 0xf8, 0x12, 0x6d, 0x97, 0x45, 0x16, 0xbb, 0x2d, 0xe5, 0x82, 0xa6, 0x34, 0x55, 0x7a,
	0x6f, 0x92, 0x9a, 0x65, 0x74, 0x03, 0x6d, 0x5d, 0x03, 0x84, 0x60, 0x10, 0x46, 0x6e, 0xb4, 0x08,
	0x6b, 0x2d, 0x27, 0x47, 0xcc, 0x8b, 0x16, 0xee, 0xd4, 0x36, 0xe4, 0xa4, 0xe0, 0x1b, 0x0f, 0x13,
	0x6f, 0x12, 0xe2, 0x52, 0x6b, 0x6e, 0xc3, 0x08, 0xcf, 0xf4, 0x6c, 0x44, 0x58, 0xce, 0x86, 0x6c,
	0xe9, 0x0b, 0xe2, 0x5e, 0x46, 0x76, 0x6b, 0xf4, 0x47, 0xe8, 0xd6, 0x8a, 0x85, 0x1c, 0x78, 0x39,
	0xc3, 0x61, 0xe8, 0x5e, 0x3d, 0x11, 0x05, 0x39, 0xdf, 0x53, 0x4c, 0x22, 0xdd, 0xd4, 0x8b, 0xf9,
	0x85, 0x16, 0x04, 0x80, 0xb6, 0xe7, 0xfa, 0x1e, 0x9e, 0xda, 0x0d, 0x29, 0x4e, 0xae, 0xf7, 0x5e,
	0xc7, 0xc7, 0x84, 0x04, 0xc4, 0x6e, 0x8d, 0x3c, 0x68, 0xa9, 0x02, 0xa2, 0xe7, 0xd0, 0x0f, 0xbd,
	0xe0, 0x41, 0x48, 0x80, 0xf6, 0x7c, 0xf1, 0x76, 0x3a, 0xf1, 0x6c, 0x03, 0x0d, 0x00, 0x08, 0x0e,
	0x23, 0x32, 0x29, 0x87, 0x5a, 0x09, 0xcd, 0xe4, 0x5a, 0x8d, 0xe0, 0x87, 0xb6, 0xea, 0xda, 0xaf,
	0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xe0, 0xfb, 0x83, 0x2a, 0x0d, 0x00, 0x00,
}
